# Vocal Guru Service - AI Voice Instructors

import atexit
import logging
import os
import tempfile
import time

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

# Fix #10: Track and clean up generated temp audio files
_generated_audio_files: list[str] = []

def _cleanup_audio_files():
    """Delete all temp audio files generated by TTS."""
    for path in _generated_audio_files:
        try:
            if os.path.exists(path):
                os.remove(path)
        except OSError:
            pass
    _generated_audio_files.clear()

atexit.register(_cleanup_audio_files)

# Try to import TTS providers
ELEVENLABS_AVAILABLE = False
GTTS_AVAILABLE = False

try:
    import elevenlabs
    ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY", "")
    if ELEVENLABS_API_KEY and len(ELEVENLABS_API_KEY) > 10:
        try:
            elevenlabs.set_api_key(ELEVENLABS_API_KEY)
        except AttributeError:
            # Newer versions use ElevenLabs(api_key=...) instead
            pass
        ELEVENLABS_AVAILABLE = True
except (ImportError, Exception) as e:
    logger.info(f"ElevenLabs not available: {e}")

try:
    from gtts import gTTS
    GTTS_AVAILABLE = True
except ImportError:
    logger.info("gTTS not installed")


# Guru personas with different teaching styles
GURU_PERSONAS = {
    "classical": {
        "name": "Pandit Ravi",
        "description": "A classical music maestro with decades of experience",
        "style": "traditional",
        "voice_id": "pNInz6obpgDQGcFmaJgB",  # ElevenLabs voice
        "greeting": "Namaste! I am Pandit Ravi. Let us begin your journey into classical music.",
        "specialties": ["raga", "tal", "classical scales", "voice training"]
    },
    "contemporary": {
        "name": "Maya Singh",
        "description": "A modern vocal coach specializing in contemporary styles",
        "style": "modern",
        "voice_id": "21m00Tcm4TlvDq8ikWAM",  # ElevenLabs voice
        "greeting": "Hey there! I'm Maya. Ready to find your unique voice?",
        "specialties": ["pop", "rock", "jazz", "improvisation"]
    },
    "carnatic": {
        "name": "Smt. Priya",
        "description": "Carnatic music expert with soulful teaching approach",
        "style": "devotional",
        "voice_id": "EXAVITQu4vr4xnSDxMaL",  # ElevenLabs voice
        "greeting": "Welcome, dear student. I am Priya. Let us explore the beauty of Carnatic music.",
        "specialties": ["carnatic", "swaras", "gamakas", "bhajans"]
    },
    "light": {
        "name": "Ustad Farid",
        "description": "Light classical and thumri specialist with a warm, conversational style",
        "style": "conversational",
        "voice_id": "pNInz6obpgDQGcFmaJgB",
        "greeting": "Adaab! I am Ustad Farid. Let us explore the expressive world of light classical music.",
        "specialties": ["thumri", "dadra", "bhajan", "ghazal", "light classical"]
    }
}

# Lesson content for different topics
GURU_LESSONS = {
    "breathing": {
        "title": "Breathing Techniques",
        "explanation": {
            "what": "Diaphragmatic breathing — the foundation of all vocal control. You breathe from the belly, not the chest.",
            "why": "Every note you sing is powered by breath. Without steady airflow, pitch wavers, volume drops, and phrases break apart.",
            "notice": "Your belly should push outward on inhale and draw inward on exhale. Your chest and shoulders should stay relaxed.",
            "practice": "You will practice a 4-count inhale, 2-count hold, 6-count exhale cycle. Place one hand on your belly to feel the movement."
        },
        "exercise": {
            "name": "Controlled Breath Cycle",
            "objective": "Develop steady diaphragmatic breath support for sustained vocal phrases.",
            "instructions": [
                "Place one hand on your belly, one on your chest.",
                "Inhale through your nose for 4 counts — feel your belly expand.",
                "Hold for 2 counts — keep your body relaxed.",
                "Exhale through your mouth for 6 counts — feel your belly draw in.",
                "Repeat 5 times."
            ],
            "duration": "3 minutes",
            "listen_for": "Belly movement vs. chest movement. If your chest rises first, you are breathing shallow.",
            "success_criteria": "Belly rises on inhale, chest stays relatively still, exhale is smooth and controlled."
        },
        "feedback_templates": {
            "good": {
                "observation": "Your breath cycle was steady and your belly showed good movement.",
                "why": "This means your diaphragm is engaging properly, giving you better vocal support.",
                "try": "Try extending the exhale to 8 counts for greater breath endurance."
            },
            "improve_shallow": {
                "observation": "Your chest was moving more than your belly during breathing.",
                "why": "Chest breathing limits your air capacity and creates tension in the throat.",
                "try": "Try lying on your back with a book on your belly. Watch it rise on inhale and fall on exhale. This trains the diaphragm."
            },
            "improve_short": {
                "observation": "Your exhale was shorter than the target duration.",
                "why": "A controlled exhale is what powers your singing phrases. Short breaths lead to short, unsupported notes.",
                "try": "Start with a 4-count inhale and 4-count exhale. Gradually increase the exhale as it becomes comfortable."
            }
        },
        "correction_exercises": {
            "shallow": "Lie down with a book on your belly. Breathe so the book rises on inhale and falls on exhale. Do 10 cycles.",
            "short": "Inhale for 4, exhale for a count you can sustain comfortably. Repeat, adding 1 count to exhale each day.",
            "default": "Practice the breath cycle again, focusing on slow, steady exhale."
        },
        "steps": [
            "Place one hand on your chest and one on your belly",
            "Breathe in slowly through your nose for 4 counts",
            "Feel your belly expand, not your chest",
            "Hold for 2 counts",
            "Exhale slowly through your mouth for 6 counts",
            "Repeat 10 times"
        ],
        "tips": [
            "Practice daily for 5 minutes",
            "Always breathe from your diaphragm",
            "Keep your shoulders relaxed"
        ]
    },
    "pitch": {
        "title": "Pitch Matching",
        "explanation": {
            "what": "Pitch matching is the ability to hear a note and reproduce it accurately with your voice.",
            "why": "Accurate pitch is the most fundamental skill in singing. Without it, melodies sound wrong even if everything else is perfect.",
            "notice": "Listen to the reference note before you sing. Feel where the note sits in your voice — is it low, middle, or high in your range?",
            "practice": "You will hear a reference tone. Hum it, then sing it on 'ah'. We will measure how close your pitch is to the target."
        },
        "exercise": {
            "name": "Reference Tone Matching",
            "objective": "Match your voice to a reference pitch accurately.",
            "instructions": [
                "Listen to the reference tone for 3 seconds.",
                "Hum the note softly to yourself.",
                "Open your mouth and sing the note on 'ah' for 3 seconds.",
                "We will compare your pitch to the target."
            ],
            "duration": "4 minutes",
            "listen_for": "Whether your pitch is sharp (too high), flat (too low), or on target.",
            "success_criteria": "Pitch within 30 cents of target note. Steady tone without significant wavering."
        },
        "feedback_templates": {
            "good": {
                "observation": "Your pitch matched the reference closely and stayed steady.",
                "why": "This shows good ear-voice coordination, which is the foundation of singing in tune.",
                "try": "Try matching notes that are further apart in pitch to expand your range."
            },
            "improve_sharp": {
                "observation": "Your pitch was consistently sharp (higher than the target).",
                "why": "Singing sharp usually means too much vocal tension or pushing too much air.",
                "try": "Relax your throat and jaw. Sing softer, not louder. Let the pitch settle down naturally."
            },
            "improve_flat": {
                "observation": "Your pitch was consistently flat (lower than the target).",
                "why": "Flat singing often means insufficient breath support or the note is at the edge of your range.",
                "try": "Engage your diaphragm more. Think of the note as sitting 'on top' of the breath, not pushed from the throat."
            },
            "improve_unstable": {
                "observation": "Your pitch started on target but wavered during the sustained note.",
                "why": "Pitch instability during sustained notes usually means inconsistent breath flow.",
                "try": "Practice breathing exercises first. Then hold the note shorter (2 seconds) until it stays steady."
            }
        },
        "correction_exercises": {
            "sharp": "Sing the note softer. Place your hand on your chest — if it vibrates a lot, you are pushing too hard.",
            "flat": "Take a deeper breath. Start the note with a gentle 'h' sound to ensure airflow is present.",
            "unstable": "Hold the note for only 2 seconds. Focus on keeping it perfectly still. Only increase duration when stable.",
            "default": "Sing the note again, focusing on steady breath and relaxed throat."
        },
        "steps": [
            "Listen to the reference note carefully",
            "Hum the note gently",
            "Match your pitch to the reference",
            "Check if you're sharp or flat",
            "Adjust and try again"
        ],
        "tips": [
            "Use a piano or tuner for reference",
            "Record yourself to check progress",
            "Start with notes in your comfortable range"
        ]
    },
    "warmup": {
        "title": "Vocal Warm-up",
        "explanation": {
            "what": "A vocal warm-up gradually activates your vocal cords, breath support, and resonance before singing.",
            "why": "Cold muscles pull and tear. Warming up prevents strain and helps you sing with more control and range.",
            "notice": "Your voice should feel looser and more flexible after warming up. If anything hurts, stop immediately.",
            "practice": "You will run through lip trills, humming, and light scales. Focus on gentle, relaxed sound — not volume."
        },
        "exercise": {
            "name": "Progressive Vocal Warm-up",
            "objective": "Activate the voice gently through progressive exercises from low to medium range.",
            "instructions": [
                "Lip trills on a comfortable pitch for 30 seconds.",
                "Hum a 5-note scale (Sa Re Ga Ma Pa) slowly, rising one semitone at a time.",
                "Sing 'ma me mi mo mu' on a comfortable 5-note pattern.",
                "Do gentle tongue stretches and jaw rotations.",
                "Sing a full octave scale softly."
            ],
            "duration": "5 minutes",
            "listen_for": "Any tightness, pain, or cracking. These are signs to ease off or stop.",
            "success_criteria": "Voice feels warm and flexible. No pain or strain. Pitch is clear."
        },
        "feedback_templates": {
            "good": {
                "observation": "Your warm-up was smooth and your voice sounded clear and flexible.",
                "why": "A good warm-up prepares your voice for more demanding singing without risking strain.",
                "try": "Add some gentle arpeggios (broken chords) to further expand your warm-up range."
            },
            "improve_tension": {
                "observation": "There were signs of tension — possibly cracking, tightness, or strain.",
                "why": "Tension in the throat restricts vocal fold movement and can lead to injury if you push through it.",
                "try": "Slow down. Do each exercise at a lower pitch where you feel comfortable. Let the voice loosen gradually."
            },
            "improve_rushed": {
                "observation": "The warm-up was done very quickly, which reduces its effectiveness.",
                "why": "Warm-ups need time to bring blood flow to the vocal folds. Rushing defeats the purpose.",
                "try": "Set a timer for 5 minutes and go through each exercise slowly. Quality matters more than speed."
            }
        },
        "correction_exercises": {
            "tension": "Hum a comfortable note for 5 seconds. If it feels tight, lower the pitch. Focus on relaxed, easy sound.",
            "rushed": "Do each exercise for 30 seconds minimum. Focus on the sensation of the voice loosening.",
            "default": "Repeat the lip trill exercise — it is the safest way to find and release tension."
        },
        "steps": [
            "Lip trills for 1 minute",
            "Humming scales up and down",
            "Tongue stretches",
            "Jaw relaxation exercises",
            "Light vocalization on 'ma', 'me', 'mi', 'mo', 'mu'"
        ],
        "tips": [
            "Never skip warm-ups",
            "Keep water nearby",
            "Stop if you feel any pain"
        ]
    },
    "sargam": {
        "title": "Sargam (Solfege) Practice",
        "explanation": {
            "what": "Sargam is the Indian solfege system: Sa Re Ga Ma Pa Dha Ni Sa. Each swara (note) has a specific position and character.",
            "why": "Sargam trains your ear to recognize intervals, builds pitch accuracy, and is the vocabulary of Indian classical music.",
            "notice": "Each note should be distinct and clear. Listen for the character of each swara — they are not just pitches, they have personality.",
            "practice": "You will sing the ascending and descending scale, then practice common sargam patterns. Focus on clarity and evenness."
        },
        "exercise": {
            "name": "Sargam Scale and Patterns",
            "objective": "Sing the sargam scale accurately and practice common melodic patterns.",
            "instructions": [
                "Sing Sa and hold for 4 beats — establish a clear, steady tone.",
                "Move to Re, then Ga, Ma, Pa, Dha, Ni, Sa (high). Hold each for 4 beats.",
                "Descend: Sa (high), Ni, Dha, Pa, Ma, Ga, Re, Sa.",
                "Now try the pattern: Sa Ga Re Ma Pa Dha Ni Sa (high).",
                "Repeat the pattern 3 times, maintaining steady rhythm."
            ],
            "duration": "5 minutes",
            "listen_for": "Even tone across all notes. Each swara should be clear and distinct, not blurred.",
            "success_criteria": "All 8 notes are clear and in tune. Pattern is rhythmic and even. No wavering between notes."
        },
        "feedback_templates": {
            "good": {
                "observation": "Your sargam was clear and each swara was distinct.",
                "why": "This is the foundation of all Indian classical singing. Clear sargam means strong ear-voice coordination.",
                "try": "Try faster patterns or add rhythmic variations using a tabla beat."
            },
            "improve_blur": {
                "observation": "Some notes blurred into each other instead of being clearly separated.",
                "why": "Blurred notes usually mean the pitch transition is not precise, or the voice is sliding between swaras.",
                "try": "Pause briefly between each note. Make each swara a separate, complete sound before moving to the next."
            },
            "improve_pitch_drift": {
                "observation": "Your pitch drifted from the tonic (Sa) as you went higher or lower.",
                "why": "Pitch drift means your internal reference to Sa is weakening. This is common when moving to extreme notes.",
                "try": "Keep a drone (tanpura or app) playing at Sa. Check back with it between each note."
            }
        },
        "correction_exercises": {
            "blur": "Sing each note as a separate sound: Sa. Pause. Re. Pause. Ga. Pause. Build clarity before speed.",
            "pitch_drift": "Sing Sa, then sing the note you drifted on. Check against the drone. Adjust until it matches. Repeat.",
            "default": "Sing the ascending scale slowly, focusing on one note at a time."
        },
        "steps": [
            "Sing Sa slowly and hold for 4 beats",
            "Move to Re, maintaining the same volume and tone",
            "Continue up the scale: Ga, Ma, Pa, Dha, Ni, Sa_high",
            "Sing the scale descending: Sa_high, Ni, Dha, Pa, Ma, Ga, Re, Sa",
            "Practice with a steady rhythm, using a tabla or metronome",
            "Try singing sargam patterns: Sa Ga Re Ma Pa Dha Ni Sa_high"
        ],
        "tips": [
            "Start slow, speed comes with practice",
            "Keep your voice steady, avoid wavering",
            "Use a tanpura or drone for reference pitch"
        ]
    },
    "raga_basics": {
        "title": "Raga Fundamentals",
        "explanation": {
            "what": "A raga is a melodic framework — more than a scale. It has rules about which notes to use, how to approach them, and what mood (rasa) it evokes.",
            "why": "Raga is the soul of Indian classical music. Understanding ragas lets you improvise, compose, and express deep musical ideas.",
            "notice": "Each raga has characteristic phrases (pakad), emphasized notes (vadi/samvadi), and a time of day it is associated with.",
            "practice": "You will learn the ascending and descending notes of a basic raga, then practice its characteristic phrases."
        },
        "exercise": {
            "name": "Raga Phrase Practice",
            "objective": "Learn and sing the characteristic phrases of a basic raga.",
            "instructions": [
                "Listen to the ascending (arohana) and descending (avarohana) notes.",
                "Sing the ascending scale, skipping any notes that are omitted in this raga.",
                "Sing the descending scale with the same rules.",
                "Learn the pakad — the signature phrase that identifies this raga.",
                "Sing the pakad slowly, then try improvising around it."
            ],
            "duration": "6 minutes",
            "listen_for": "The character of the raga. Does it feel peaceful, devotional, playful, or melancholic?",
            "success_criteria": "You can sing the arohana, avarohana, and pakad accurately. The raga's mood is present in your singing."
        },
        "feedback_templates": {
            "good": {
                "observation": "You captured the essential notes and character of the raga.",
                "why": "This means you are hearing the raga as a musical idea, not just a sequence of notes.",
                "try": "Explore the raga's vadi (king note) and samvadi (queen note). Emphasize them in your phrases."
            },
            "improve_notes": {
                "observation": "Some notes from the raga were incorrect or missing.",
                "why": "Raga identity depends on specific notes. Wrong notes break the raga's character.",
                "try": "Practice the arohana and avarohana slowly until each note is automatic before trying phrases."
            },
            "improve_phrases": {
                "observation": "The notes were correct but the phrases lacked the raga's character.",
                "why": "Raga is not just notes — it is how you approach and leave them. Phrasing brings the raga to life.",
                "try": "Listen to a master's recording of this raga. Notice how they approach the vadi note and how they phrase transitions."
            }
        },
        "correction_exercises": {
            "notes": "Write down the arohana and avarohana. Sing them slowly with a drone until each note is accurate.",
            "phrases": "Learn 3 standard phrases of this raga. Sing each one 5 times before trying to improvise.",
            "default": "Sing the raga's arohana and avarohana again, focusing on each note's character."
        },
        "steps": [
            "Understand that a raga is more than a scale — it has mood, time, and character",
            "Learn the ascending (arohana) and descending (avarohana) notes",
            "Identify the vadi (king note) and samvadi (queen note)",
            "Practice characteristic phrases (pakad) of the raga",
            "Explore the raga at its prescribed time of day",
            "Listen to recordings of masters performing this raga"
        ],
        "tips": [
            "Each raga has a specific emotional flavor (rasa)",
            "Some notes are skipped or emphasized in certain ragas",
            "Practice one raga deeply before moving to the next"
        ]
    },
    "ornamentation": {
        "title": "Murki & Gamak (Ornamentation)",
        "explanation": {
            "what": "Ornamentation (alankar) includes meend (glide), murki (quick note cluster), gamak (oscillation), and andolan (gentle shake).",
            "why": "Ornaments add expression and emotion to a raga. They distinguish a flat rendition from a living, breathing performance.",
            "notice": "Each ornament has a specific technique. Meend is smooth, murki is quick, gamak is oscillating. They serve different expressive purposes.",
            "practice": "You will practice meend first — the most fundamental ornament. Then try murki on a single note."
        },
        "exercise": {
            "name": "Meend and Murki Practice",
            "objective": "Produce smooth meend (glides) between notes and quick murki clusters.",
            "instructions": [
                "Sing Sa and glide smoothly to Ga without stopping — this is meend.",
                "Hold Sa briefly, quickly touch Re, and return to Sa — this is murki.",
                "Practice meend: Sa to Ga, Ga to Sa, Re to Ma, Ma to Re.",
                "Practice murki on each note of the scale.",
                "Combine: sing a phrase with meend, then add murki."
            ],
            "duration": "5 minutes",
            "listen_for": "Smoothness of meend (no breaks) and crispness of murki (no blurring).",
            "success_criteria": "Meend is continuous and smooth. Murki is quick and distinct. Both feel natural in context."
        },
        "feedback_templates": {
            "good": {
                "observation": "Your meend was smooth and your murki was crisp.",
                "why": "These ornaments are the foundation of expressive Indian classical singing.",
                "try": "Practice gamak — oscillation between two notes — to add another ornament to your toolkit."
            },
            "improve_broken_meend": {
                "observation": "Your meend had breaks or was not continuous between notes.",
                "why": "A broken meend loses its expressive power. The glide should be one unbroken motion.",
                "try": "Sing the two notes at a very low volume and slide between them. Volume is the enemy of smooth meend."
            },
            "improve_slow_murki": {
                "observation": "Your murki was too slow and sounded like three separate notes.",
                "why": "Murki must be quick — it is a single ornament, not a sequence of notes.",
                "try": "Think of the murki as a 'flick' of the voice. Start very fast, even if accuracy suffers, then refine."
            }
        },
        "correction_exercises": {
            "broken_meend": "Hum the glide at low volume. If you hear a break, the transition is not smooth enough.",
            "slow_murki": "Practice the murki as a single gesture, not individual notes. Speed up gradually.",
            "default": "Practice meend between two notes at a comfortable distance. Focus on smoothness."
        },
        "steps": [
            "Learn meend (glide) — smooth transition between notes",
            "Practice murki — a quick cluster of notes around the main note",
            "Try gamak — oscillation between two adjacent notes",
            "Explore andolan — a gentle oscillation on specific notes",
            "Combine ornaments in simple phrases",
            "Record yourself and compare with masters"
        ],
        "tips": [
            "Ornaments should enhance, not overwhelm the melody",
            "Different ragas have different ornamentation rules",
            "Start with simple meend, progress to complex gamaks"
        ]
    },
    "rhythm": {
        "title": "Tala & Rhythm Training",
        "explanation": {
            "what": "Tala is the rhythmic cycle in Indian classical music. Teental (16 beats) is the most common. It has sam (beat 1), khali (empty beat), and tali (clap beats).",
            "why": "Rhythm is the heartbeat of music. Without steady rhythm, even beautiful melodies sound chaotic and lose their impact.",
            "notice": "Feel the sam as a point of resolution. Everything in the tala cycle builds toward and returns to the sam.",
            "practice": "You will clap the basic Teental cycle, sing a sargam pattern within it, and practice ending phrases on the sam."
        },
        "exercise": {
            "name": "Tala Cycle and Pattern Practice",
            "objective": "Maintain a steady tala and sing rhythmic patterns that resolve on sam.",
            "instructions": [
                "Clap Teental: Clap on 1, 5, 9, 13. Wave on beat 13 (khali). This is the 16-beat cycle.",
                "Sing 'Dha' on every beat for 2 cycles. Keep the clapping steady.",
                "Now sing the pattern: Sa Re Ga Ma (4 beats), Pa Dha Ni Sa (4 beats), Ni Dha Pa Ma (4 beats), Ga Re Sa (4 beats ending on sam).",
                "Repeat the pattern, making sure you land on Sa exactly on the sam (beat 1).",
                "Try a faster version if the slow one is comfortable."
            ],
            "duration": "5 minutes",
            "listen_for": "Whether your singing aligns with the clapping. The sam should feel like a satisfying resolution.",
            "success_criteria": "Clapping is steady. Singing aligns with beats. Phrase ends exactly on sam."
        },
        "feedback_templates": {
            "good": {
                "observation": "Your tala was steady and your phrases resolved cleanly on sam.",
                "why": "This is the essence of rhythmic singing — phrases that breathe within the tala cycle.",
                "try": "Try layakari: sing 2 notes per beat (dugun) or 4 notes per beat (chaugun) within the same tala."
            },
            "improve_rushing": {
                "observation": "Your singing was faster than the tala, causing you to arrive at sam too early.",
                "why": "Rushing usually means the tala is not internalized yet. The tala should feel effortless.",
                "try": "Slow down the tala. Clap and sing at a pace where you never lose track of which beat you are on."
            },
            "improve_late": {
                "observation": "Your singing was behind the tala, causing you to arrive at sam too late.",
                "why": "Singing behind the tala usually means the pattern is too complex for the current tempo.",
                "try": "Simplify the pattern. Use fewer notes per beat until you can stay locked to the tala."
            }
        },
        "correction_exercises": {
            "rushing": "Clap the tala without singing. Internalize the cycle. Then add singing at half the speed.",
            "late": "Sing simple notes on each beat — one note per clap. Build from this foundation.",
            "default": "Clap the tala and count aloud: 1, 2, 3, 4, 5, 6, 7, 8... until the cycle feels automatic."
        },
        "steps": [
            "Clap the basic tala cycle (e.g., Teental: 16 beats)",
            "Identify the sam (first beat) and khali (empty beat)",
            "Sing a simple sargam pattern within the tala",
            "Practice layakari — doubling and halving the tempo",
            "Try singing taans (fast melodic runs) in rhythm",
            "End phrases on the sam for resolution"
        ],
        "tips": [
            "Always keep the tala steady, never rush",
            "Use a tabla or metronome for practice",
            "Start with slow tempo (vilambit), then try fast (drut)"
        ]
    }
}


def get_guru(guru_id: str) -> dict | None:
    """Get a specific guru"""
    return GURU_PERSONAS.get(guru_id)


def get_all_gurus() -> list[dict]:
    """Get all available gurus"""
    return [
        {"id": gid, **guru}
        for gid, guru in GURU_PERSONAS.items()
    ]


def get_lesson_content(topic: str) -> dict | None:
    """Get lesson content for a topic"""
    return GURU_LESSONS.get(topic.lower())


def get_available_topics() -> list[str]:
    """Get all available lesson topics"""
    return list(GURU_LESSONS.keys())


def generate_speech(text: str, guru_id: str = "classical") -> str | None:
    """
    Generate speech audio from text using TTS.
    Returns audio file path or URL.
    """
    guru = GURU_PERSONAS.get(guru_id, GURU_PERSONAS["classical"])
    timestamp = int(time.time() * 1000)
    # Sanitize guru_id for safe filename
    safe_id = ''.join(c for c in guru_id if c.isalnum() or c in ('-', '_'))[:50]

    # Try ElevenLabs first
    if ELEVENLABS_AVAILABLE:
        try:
            audio = elevenlabs.generate(
                text=text,
                voice=guru["voice_id"],
                model="eleven_monolingual_v1"
            )
            # Save to temp file with unique name
            temp_dir = tempfile.gettempdir()
            audio_path = os.path.join(temp_dir, f"guru_{safe_id}_{timestamp}.mp3")
            with open(audio_path, "wb") as f:
                f.write(audio)
            _generated_audio_files.append(audio_path)
            return audio_path
        except Exception as e:
            logger.error(f"ElevenLabs error: {e}")

    # Fallback to gTTS
    if GTTS_AVAILABLE:
        try:
            tts = gTTS(text=text, lang='en')
            temp_dir = tempfile.gettempdir()
            audio_path = os.path.join(temp_dir, f"guru_{safe_id}_{timestamp}.mp3")
            tts.save(audio_path)
            _generated_audio_files.append(audio_path)
            return audio_path
        except Exception as e:
            logger.error(f"gTTS error: {e}")

    return None


def generate_greeting(guru_id: str) -> dict:
    """Generate a greeting from the guru"""
    guru = GURU_PERSONAS.get(guru_id, GURU_PERSONAS["classical"])
    return {
        "guru_id": guru_id,
        "name": guru["name"],
        "greeting": guru["greeting"],
        "specialties": guru["specialties"],
        "audio_available": ELEVENLABS_AVAILABLE or GTTS_AVAILABLE
    }


def generate_lesson_speech(topic: str, guru_id: str = "classical") -> dict:
    """Generate speech for a lesson"""
    lesson = GURU_LESSONS.get(topic.lower())
    if not lesson:
        return {"error": "Topic not found"}

    guru = GURU_PERSONAS.get(guru_id, GURU_PERSONAS["classical"])

    # Combine all steps into speech
    full_text = f"{guru['name']} says: {lesson['title']}. "
    full_text += "Let me guide you through this. "
    for i, step in enumerate(lesson["steps"], 1):
        full_text += f"Step {i}: {step}. "
    full_text += "Remember these tips: "
    for tip in lesson["tips"]:
        full_text += f"{tip}. "

    return {
        "guru_id": guru_id,
        "guru_name": guru["name"],
        "topic": topic,
        "title": lesson["title"],
        "steps": lesson["steps"],
        "tips": lesson["tips"],
        "speech_text": full_text,
        "audio_available": ELEVENLABS_AVAILABLE or GTTS_AVAILABLE
    }